eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign555
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    timeout: 1000
  data:
    solr:
      host: http://localhost:8090/solr
  mongodb:
      uri: mongodb://localhost:27017/xwy1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    
feign:
    hystrix:
        enabled: true
