server:
  port: 8081

spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/1809b?ServerTimeZone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

  instance:
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml
feign:
  httpclient:
    enabled: true
